# Generated by Django 3.0.5 on 2020-06-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0003_auto_20200617_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('gestor', 'Gestor')], default='gestor', max_length=7),
        ),
    ]
