# Generated by Django 3.0.5 on 2020-06-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0004_administrador_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendaonline.Categoria'),
        ),
    ]
