# Generated by Django 3.0.5 on 2020-06-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0006_auto_20200620_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.ImageField(upload_to='static/imgproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaonline.Producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
