# Generated by Django 3.0.5 on 2020-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0006_auto_20200607_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='promocion',
            field=models.PositiveIntegerField(),
        ),
    ]
