# Generated by Django 3.0.5 on 2020-06-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0007_auto_20200620_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tiendaonline.Producto'),
        ),
    ]
