# Generated by Django 3.0.5 on 2020-06-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0009_auto_20200607_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='producto',
            field=models.ManyToManyField(to='tiendaonline.Producto'),
        ),
    ]
