# Generated by Django 3.0.5 on 2020-06-29 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaonline', '0011_auto_20200629_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='nombreArchivo',
            new_name='imagen',
        ),
    ]
